whittier/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # devise_for :users, controllers: { registrations: 'registrations' }
  # get 'carts/show'
  post 'clothings/add_to_cart/:id', to: 'clothings#add_to_cart', as: 'add_to_cart'
  delete 'clothings/remove_from_cart/:id', to: 'clothings#remove_from_cart', as: 'remove_from_cart'

  get 'searches/index'
  get 'contacts/index'
  get 'home/index'
  get 'home/edit'
  get 'clothings/index'
  get 'clothings/tops'
  get 'clothings/bottoms'
  get 'clothings/jackets'
  get 'clothings/footwear'
  get 'clothings/accessory'
  get 'clothings/show/:id', to: 'clothings#show', as: 'clothing'
  get 'about/index'
  root to: 'clothings#index'
  resources :searches
  resources :clothing_orders
  resource :carts, only: [:show]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

whittier/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

whittier/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

whittier/app/models/clothing.rb
# frozen_string_literal: true

class Clothing < ApplicationRecord
  has_many :clothing_orders
  has_many :orders, through: :clothing_orders

  validates :name, :price, :clothing_type, presence: true
  validates :price, numericality: true

  has_one_attached :image

  def self.search(search)
    if search
      where(['name LIKE ?', "%#{params[:search]}%"]) if search
    else
      all
    end
  end
end

whittier/app/models/clothing_order.rb
# frozen_string_literal: true

class ClothingOrder < ApplicationRecord
  belongs_to :clothing
  belongs_to :order

  def unit_price
    if persisted?
      self[:unit_price]
    else
      clothing.price
    end
  end

  def total
    unit_price * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total
    self[:total] = total * quantity
  end
end

whittier/app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user
  has_many :clothing_orders
  has_many :clothing, through: :clothing_orders

  before_save :set_subtotal

  def subtotal
    clothing_orders.collect { |clothing_order| clothing_order.valid? ? clothing_order.unit_price * clothing_order.quantity : 0 }.sum
  end

  private

  def set_subtotal
    self[:subtotal] = subtotal
  end
end

whittier/app/models/province.rb
class Province < ApplicationRecord
end

whittier/app/models/search.rb
# frozen_string_literal: true

class Search < ApplicationRecord
  def search_books
    clothes = Clothing.all
    if keywords.present?
      clothes = Clothing.where(['name LIKE ?', "%#{keywords}%"])
    end
    if category.present?
      clothes = Clothing.where(['clothing_Type LIKE ?', category])
    end
    clothes = Clothing.where(['price >= ?', min_price]) if min_price.present?
    clothes = Clothing.where(['price <= ?', max_price]) if max_price.present?
    clothes = Clothing.where(['brand LIKE ?', brand]) if brand.present?

    clothes
  end
end

whittier/app/models/user.rb
class User < ApplicationRecord
  has_one :provinces
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

whittier/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

whittier/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  end
end

whittier/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end
end

whittier/app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    random_number = rand(1..Clothing.count)
    @clothes = Clothing.where(id: random_number)
  end

  def edit; end
end

whittier/app/helpers/about_helper.rb
module AboutHelper
end

whittier/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

whittier/app/helpers/carts_helper.rb
module CartsHelper
end

whittier/app/helpers/clothing_orders_helper.rb
module ClothingOrdersHelper
end

whittier/app/helpers/clothings_helper.rb
module ClothingsHelper
end

whittier/app/helpers/contacts_helper.rb
module ContactsHelper
end

whittier/app/helpers/home_helper.rb
module HomeHelper
end

whittier/app/helpers/searches_helper.rb
module SearchesHelper
end

whittier/app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="notification is-danger-<%= key %>">
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

whittier/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Whittier</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <link rel="stylesheet" href="whittier/app/assets/stylesheets/clothings.scss">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  </head>
    <div class="container">
      <header>
        <nav class="navbar">
            <div class="navbar-menu">
              <h1 class="title is-1">whittier.</h1>
              <div class="navbar-end">
                <div class="navbar-item is-hoverable">
                  <%= link_to "tops", clothings_tops_path %>
                </div>

                <div class="navbar-item is-hoverable">
                  <%= link_to "bottoms", clothings_bottoms_path  %>
                </div>

                <div class="navbar-item is-hoverable">
                  <%= link_to "jackets", clothings_jackets_path  %>
                </div>

                <div class="navbar-item is-hoverable">
                  <%= link_to "footwear", clothings_footwear_path  %>
                </div>

                <div class="navbar-item is-hoverable">
                  <%= link_to "accessory", clothings_accessory_path  %>
                </div>

                <div class="navbar-item is-hoverable">
                  <%= link_to "advanced search", new_search_path  %>
                </div>
                <% if current_user %>
                  <div class="navbar-item is-hoverable"></div>
                    <%= link_to 'sign out', destroy_user_session_path, method: :delete %>
                  </div>
                  <% else %>
                    <div class="navbar-item is-hoverable">
                      <%= link_to 'sign in', new_user_session_path %>
                    </div>
                    <div class="navbar-item is-hoverable">
                      <%= link_to 'sign up', new_user_registration_path %>
                    </div>
                <% end %>
              </div>
            </div>
          </nav>
      </header>
  </div>
  <section class="section">
    <div class="container">
        <% if notice %>
          <div class="notification is-success">
            <%= notice %>
          </div>
        <% end%>
        <% if alert %>
          <div class="notification is-danger">
            <%= alert %>
          </div>
        <% end%>
        <%= render_breadcrumbs %>
        <%= yield %>
    </div>
  </section>
</html>