whittier/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # devise_for :users, controllers: { registrations: 'registrations' }
  # get 'carts/show'
  post 'clothings/add_to_cart/:id', to: 'clothings#add_to_cart', as: 'add_to_cart'
  delete 'clothings/remove_from_cart/:id', to: 'clothings#remove_from_cart', as: 'remove_from_cart'

  get 'searches/index'
  get 'contacts/index'
  get 'home/index'
  get 'home/edit'
  get 'clothings/index'
  get 'clothings/tops'
  get 'clothings/bottoms'
  get 'clothings/jackets'
  get 'clothings/footwear'
  get 'clothings/accessory'
  get 'clothings/show/:id', to: 'clothings#show', as: 'clothing'
  get 'about/index'
  root to: 'clothings#index'
  resources :searches
  resources :clothing_orders
  resource :carts, only: [:show]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

whittier/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

whittier/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

whittier/app/models/clothing.rb
# frozen_string_literal: true

class Clothing < ApplicationRecord
  has_many :clothing_orders
  has_many :orders, through: :clothing_orders

  validates :name, :price, :clothing_type, presence: true
  validates :price, numericality: true

  has_one_attached :image

  def self.search(search)
    if search
      where(['name LIKE ?', "%#{params[:search]}%"]) if search
    else
      all
    end
  end
end

whittier/app/models/clothing_order.rb
# frozen_string_literal: true

class ClothingOrder < ApplicationRecord
  belongs_to :clothing
  belongs_to :order

  def unit_price
    if persisted?
      self[:unit_price]
    else
      clothing.price
    end
  end

  def total
    unit_price * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total
    self[:total] = total * quantity
  end
end

whittier/app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user
  has_many :clothing_orders
  has_many :clothing, through: :clothing_orders

  before_save :set_subtotal

  def subtotal
    clothing_orders.collect { |clothing_order| clothing_order.valid? ? clothing_order.unit_price * clothing_order.quantity : 0 }.sum
  end

  private

  def set_subtotal
    self[:subtotal] = subtotal
  end
end

whittier/app/models/province.rb
class Province < ApplicationRecord
end

whittier/app/models/search.rb
# frozen_string_literal: true

class Search < ApplicationRecord
  def search_books
    clothes = Clothing.all
    if keywords.present?
      clothes = Clothing.where(['name LIKE ?', "%#{keywords}%"])
    end
    if category.present?
      clothes = Clothing.where(['clothing_Type LIKE ?', category])
    end
    clothes = Clothing.where(['price >= ?', min_price]) if min_price.present?
    clothes = Clothing.where(['price <= ?', max_price]) if max_price.present?
    clothes = Clothing.where(['brand LIKE ?', brand]) if brand.present?

    clothes
  end
end

whittier/app/models/user.rb
class User < ApplicationRecord
  has_one :provinces
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

whittier/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

whittier/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include ApplicationHelper
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username name first_name last_name email phone_number city country address postal_code province])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username name first_name last_name email phone_number city country address postal_code province])
  end
end

whittier/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  end
end

whittier/app/controllers/clothings_controller.rb
# frozen_string_literal: true

class ClothingsController < ApplicationController
  before_action :initialize_session
  before_action :load_cart
  add_breadcrumb 'home', :root_path
  def index
    random_number = rand(1..Clothing.count)
    @clothes = Clothing.where(id: random_number)
  end

  def load_cart
    @cart = Clothing.find(session[:cart])
  end

  def add_to_cart
    id = params[:id].to_i
    session[:cart] << id unless session[:cart].include?(id)
    redirect_to root_path
    flash[:notice] = 'Successfully added to cart'
  end

  def remove_from_cart
    id = params[:id].to_i
    session[:cart].delete(id)
    redirect_to root_path
  end

  def tops
    @clothes = Clothing.where(clothing_type: :top).page(params[:page]).per(30)
    add_breadcrumb 'tops', clothings_tops_path
  end

  def bottoms
    @clothes = Clothing.where(clothing_type: :bottom).page(params[:page]).per(30)
    add_breadcrumb 'bottoms', clothings_bottoms_path
  end

  def accessory
    @clothes = Clothing.where(clothing_type: :accessory).page(params[:page]).per(30)
    add_breadcrumb 'accessory', clothings_accessory_path
  end

  def footwear
    @clothes = Clothing.where(clothing_type: :footwear).page(params[:page]).per(30)
    add_breadcrumb 'footwear', clothings_footwear_path
  end

  def jackets
    @clothes = Clothing.where(clothing_type: :jacket).page(params[:page]).per(30)
    add_breadcrumb 'jackets', clothings_jackets_path
  end

  def show
    @clothes = Clothing.find(params[:id])
    add_breadcrumb @clothes.name, clothing_path(@clothes.id)
  end

  def edit; end

  protected

  def initialize_session
    session[:visit_count] ||= 0
    session[:cart] ||= []
  end
end

whittier/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end
end

whittier/app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    random_number = rand(1..Clothing.count)
    @clothes = Clothing.where(id: random_number)
  end

  def edit; end
end

whittier/app/controllers/searches_controller.rb
# frozen_string_literal: true

class SearchesController < ApplicationController
  def new
    @search = Search.new
    @categories = Clothing.distinct.pluck(:clothing_type)
  end

  def create
    @search = Search.create(search_params)
    redirect_to @search
  end

  def show
    @search = Search.find(params[:id])
  end

  private

  def search_params
    params.require(:search).permit(:keywords, :category, :min_price, :max_price)
  end
end

whittier/app/helpers/about_helper.rb
module AboutHelper
end

whittier/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

whittier/app/helpers/carts_helper.rb
module CartsHelper
end

whittier/app/helpers/clothing_orders_helper.rb
module ClothingOrdersHelper
end

whittier/app/helpers/clothings_helper.rb
module ClothingsHelper
end

whittier/app/helpers/contacts_helper.rb
module ContactsHelper
end

whittier/app/helpers/home_helper.rb
module HomeHelper
end

whittier/app/helpers/searches_helper.rb
module SearchesHelper
end

whittier/app/views/clothings/_clothingcard.html.erb
<div class="columns is-multiline">
  <% @clothes.each do |clothing| %>
    <div class="column is-one-quarter clothingbox">
      <div class="card">
          <div class="card-image">
            <figure class="image">
              <%= image_tag clothing.image, alt:"clothes" %>
            </figure>
          </div>
        <div class="media-content">
          <strong><%= clothing.brand%></strong>
          <br>
          <br>
          <strong><%= link_to clothing.name, clothing_path(clothing.id) %></strong>
          <br>
          <br>
          <strong>$<%= clothing.price %>0</strong>
        </div>
      </div>
    </div>
  <% end %>
</div>

whittier/app/views/clothings/accessory.html.erb
<%= paginate @clothes %>
<div class="columns">
  <%= render partial: 'clothingcard',
    object: @clothes
   %>
</div>

whittier/app/views/clothings/bottoms.html.erb
  <%= paginate @clothes %>
<div class="columns">
  <%= render partial: 'clothingcard',
    object: @clothes
   %>
</div>

whittier/app/views/clothings/edit.html.erb
<h1>Clothings#edit</h1>
<p>Find me in app/views/clothings/edit.html.erb</p>

whittier/app/views/clothings/footwear.html.erb
<%= paginate @clothes %>
<div class="columns">
  <%= render partial: 'clothingcard',
    object: @clothes
   %>
   <%= paginate @clothes %>
</div>

whittier/app/views/clothings/index.html.erb
<details>
  <summary>Shopping Cart</summary>
    <% if @cart.empty? %>
      <p>Nothing in cart</p>
    <% else %>
    <ul>
      <% @cart.each do |product| %>
        <li><%= product.name %> | <%= link_to 'Remove', remove_from_cart_path(product.id), method: :delete %></li>
      <% end %>
    </ul>
    <% end %>
</details>
<br />
<section class="section">
  <%= image_tag ("store.jpg"), alt: "store image" %>
</section>

whittier/app/views/clothings/jackets.html.erb
<%= paginate @clothes %>
<div class="columns">
  <%= render partial: 'clothingcard',
    object: @clothes
   %>
</div>

whittier/app/views/clothings/show.html.erb
<div class="level">
  <div class="tile is-ancestor">
    <div class="tile is-parent">
      <div class="card">
        <div class="card-image">
          <figure class="image displaybox">
            <%= image_tag @clothes.image %>
          </figure>
        </div>
      </div>
    </div>
    <div class="tile is-parent">
      <% if @cart.include?(@clothes) %>
       <p><%= button_to 'remove from cart', remove_from_cart_path(@clothes.id), method: :delete, class: "button" %></p>
      <% else%>
        <p><%= button_to 'add to cart', add_to_cart_path(@clothes.id), method: :post, class: "button" %></p>
      <% end %>

      <h1 class="title is-3"><%= @clothes.name %></h1>
      <h2 class="subtitle is-5"><%= @clothes.brand %></h2>
      <strong>Price: <%= number_to_currency @clothes.price/1.0 %></strong>
    </div>
  </div>

</div>

whittier/app/views/clothings/tops.html.erb
<%= paginate @clothes %>
<div class="columns">
  <%= render partial: 'clothingcard',
    object: @clothes
   %>
</div>

whittier/app/views/searches/index.html.erb
<h1>Searches#index</h1>
<p>Find me in app/views/searches/index.html.erb</p>

whittier/app/views/searches/new.html.erb
<h1 class='title'>Advanced Search</h1>

<div class="box">
  <%= form_for @search, html: {class:"pure-form"} do |s| %>

  <div class="field">
    <%= s.label :keywords, class: "label" %>
    <div class="control">
      <%= s.text_field :keywords, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= s.label :category %> <br>
    <div class="control">
      <%= s.select :category, options_for_select(@categories), :include_blank => true, :class => "select"  %>
    </div>
  </div>

  <div class="field">
    <p><%= s.label :min_price, "Min Price"  %> <%= s.text_field :min_price, size:10, class: "input" %></p>
    <p><%= s.label :max_price, "Max Price"  %><%= s.text_field :max_price, size:10, class: "input" %></p>
  </div>

  <div class="actions">
    <%= s.submit "Search", class: "button is-primary" %>
  </div>
<% end %>
</div>

whittier/app/views/searches/show.html.erb
<h1 class="title">Search Results</h1>

<% if @search.search_books.empty? %>
  <p>No Records Found</p>
<% else %>
  <% @search.search_books.each do |c| %>
    <br>
    <div class="">
      <h1><%= link_to c.name, clothing_path(c.id) %></h1>
      <p>Price: $<%= c.price %></p>
      <p>Category: <%= c.clothing_type %></p>
    </div>
  <% end %>
<% end %>